# Dummy Remix Challenge

??? info "About Remix Challenges"
    Welcome the Remix Challenges. We find an existing 3D file and generate a walkthough tutorial so you can recreate it yourself. All of our remixes are designed to be printed. We'll provide video and proof of the printed version.

## Original

??? quote "Original Creator Info"
    ![](https://cdn.thingiverse.com/assets/22/2e/66/3b/a5/large_display_target_render2.jpg){ width="300" }

    - **Name:** Target Dummy2
    - **Creator:** InfityModels
    - **Date:** March 11, 2022
    - **URL:** https://www.thingiverse.com/thing:5294269

## **Full Video**

<iframe width="560" height="315" src="https://www.youtube.com/embed/B0cwV9C5Uro?si=CuPaZrxRYUfKNma1" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

## **Guided Tutorial**

For this tutorial we will be making a Target Dummy using the TinkerCAD tool. We will print this a Sovol SV06 Plus 3D Printer.



1. To begin, open a browser and go to TinkerCAD.com
2. Login and create a new project. Name it: **Target Dummy**

    ### :material-arrow-right-box: Create the Base Unit

    <iframe width="560" height="315" src="https://www.youtube.com/embed/B0cwV9C5Uro?start=115&end=187;" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

3. The first piece we will create is the base with the center post stopping point. Drag in a cylinder to the stage and resize it using the following dimensions.

    ```py
    width   [x]: 40 mm
    length  [y]: 40 mm
    height  [z]: 4 mm
    ```

    ### :material-arrow-right-box: Add the Support Rod

    <iframe width="560" height="315" src="https://www.youtube.com/embed/B0cwV9C5Uro?start=187&end=436" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

4. Now, duplicate the cylinder and resize the duplicate to:

    ```py
    width   [x]: 5.25 mm
    length  [y]: 5.25 mm
    height  [z]: 50 mm
    ```

5. Center the tall cylinder to the base plate.
6. Duplicate the long cylinder, change it's color (not required), and resize it to:

    ```py
    width   [x]: 7 mm
    length  [y]: 7 mm
    height  [z]: 12 mm
    ```

7. Now expand the setting for this third cylinder and set:

    ```py
    Sides: 64
    Bevel: 2.5
    Segments: 1
    ```

8. Now align all three cylinders to the center of the base unit and to the bottom of the base unit.

    ### :material-arrow-right-box: Create the Dummies Head

    <iframe width="560" height="315" src="https://www.youtube.com/embed/B0cwV9C5Uro?start=436&end=589" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

9. Next, let's add the Head by Duplicating the long cylinder. It helps to recolor it.

10. Set the dimensions and settings of this new object to:

    ```py
    width   [x]: 16 mm
    length  [y]: 16 mm
    height  [z]: 19 mm

    Sides: 12
    Bevel: 2.5
    Segments: 1
    ```

11. Align it to the center-top of the long cylinder. Then temporarily turn it from a solid to a hole. We do this so we can see where it's physically located to other objects.

12. Move it vertically up so the long cylinder end is in the middle of it.

    ### :material-arrow-right-box: Create the Dummies Body

    <iframe width="560" height="315" src="https://www.youtube.com/embed/B0cwV9C5Uro?start=589&end=846" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

13. With the head created, the next step is to begin creating the body.
14. The body is made up of four shapes. A cylinder for the lower body and four spheres for the upper. Let's create the upper first.

15. Add a sphere and align it to the center of the long cylnders which is apart of the base. Align it to the top and drag it down a little bit.

16. Squish the sphere front and back while still retaining the rounded features on the sides.

17. Duplicate the sphere and convert to a hole. Drag it up toward the top of the solid sphere. Stop the bottom of it right before the shoulders or where you imagine the shoulders would be.

18. Duplicate he solid spear once more and change it's color. Squish from top to bottom.

19. Now group the Solid Sphere with the Hold Sphere. Then move the squished sphere you just created upwards into the new holed out area and shrink it down so it looks like part of a body.



