site_name: FundedYouth Docs
site_description: A comprehensive documentation site for FundedYouth
site_url: https://FundedYouth.github.io/mkdocs

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.mark
  - attr_list
  - admonition
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - md_in_html

theme:
  name: material
  language: en
  logo: assets/logo.png
  favicon: assets/favicon.ico
  features:
    - navigation.top
    # - navigation.tabs
    - navigation.indexes
    - navigation.sections
    # - navigation.instant
    # - navigation.path
    - search.suggest
    - search.highlight
    - content.code.annotation
    - content.code.copy
    - content.tabs.link
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: deep purple
      accent: teal
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      primary: deep purple
      accent: teal

extra:
  social:
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/FundedYouthOrg
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/FundedYouth/
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/FundedYouth
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/fundedyouth/
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@FundedYouth

plugins:
  - search
  # - glightbox
  - blog:
      archive_name: Archive
      archive_toc: true
      categories: true
      pagination_per_page: 5
      authors_profiles: true



copyright: Copyright &copy; <script>document.write(new Date().getFullYear())</script> <a href="https://FundedYouth.org">FundedYouth 501(c)3</a>

extra_css:
  - stylesheets/style.css


nav:
  - 'Welcome': 'README.md'
  # - 'Instructors': './Instructors'
  - 'Nonprofit':
    - 'Get Started': './Nonprofit'
    - 'Open Labs': './Nonprofit/Open_Labs'
    - 'Branding': './Nonprofit/Branding'
    - 'External Services': './Nonprofit/External_Services'
    - 'Members and Meetings': './Nonprofit/Board_Members'
    - 'Pricing Models': ''
  - 'Tutorials':
    - 'Overview': './Tutorials'
    - 'Remix Challenges': './Tutorials/Remix_Challenge'
    - 'Hardware': './Tutorials/Hardware_Setup'
    - 'TinkerCAD': './Tutorials/TinkerCAD'
    # - 'OnShape': ''
    # - 'Lasercraft': ''
  - 'Blog': './blog'

