authors:
  ryan_jones:
    name: Ryan Jones M.Ed.
    description: Director
    avatar: https://media.licdn.com/dms/image/v2/D5603AQHkGiHOIjc_gQ/profile-displayphoto-shrink_200_200/profile-displayphoto-shrink_200_200/0/1705018613106?e=1732147200&v=beta&t=KgXinAzKdLYKdSu9ulyV1-p7LvP6U3p62WRbPowbpZQ

  jeff_guentner:
    name: Jeff Guentner
    description: Designer
    avatar: https://media.licdn.com/dms/image/v2/D4E03AQHXbyThULCnJA/profile-displayphoto-shrink_100_100/profile-displayphoto-shrink_100_100/0/1710199243695?e=1732147200&v=beta&t=iS3AzzZZPoaKFi5ruxw3gZW7FAd3cVzzaKM3XctLzEo